---
title: 污名化
author: Ruiyang Yao
date: '2020-05-04'
slug: stigmatization
categories:
  - R
tags:
  - R Markdown
output: 
  html_document: 
    theme: cerulean
    toc: yes
---

> 污名化是一个群体将**贬低化标签**强加在另一个群体之上并加以维持的动态过程，它是将**群体**的**偏向负面的特征刻板印象化**，并由此掩盖其他特征，成为在本质意义上与群体特征对应的指标物。蒙受污名者通常会遭受到人际排斥，他们逐渐丧失社会地位和信誉，丧失自尊心、自信心，凝滞在弱势状态，极难向上一阶层流动。

# 1.污名化概念的完善
```{R, echo=FALSE}
DiagrammeR::grViz("

digraph RmarkDown {
graph [rankdir = TB]
node [shape=rectangle
  style=filled
  color=red
  fillcolor=orange
  fontcolor=white
  arrowcolor=red
  alpha=65
  fontname = '楷体']
edge [color = grey]
'①来源于古希腊' -> '②Goffman将污名引入到心理学的研究领域'
'②Goffman将污名引入到心理学的研究领域' -> '③Kurzban等从进化论视角提出另一个定义'
'③Kurzban等从进化论视角提出另一个定义' -> '④Link等人重新定义污名的概念'
     }
    ", width=300)
```

## 最早**来源**于古希腊          
   &emsp;&emsp;**含义**：  
   &emsp;&emsp;是一种**身体标记**。这种标记是刻在或烙在某些人身上，表示带有这种标记的人**不受欢迎**，需要回避和远离。

## Goffman将污名引入到**心理学**的研究领域  
   &emsp;&emsp;**观点**：         
   &emsp;&emsp;将污名**定义**为个体的一种不被信任和不受欢迎的特征，这种特征降低了个体在社会中的地位，使他从一个完美的、有用的个体变成了一个有污点和丧失了部分价值的人，是社会对某些个体或群体贬低性、侮辱性的标签。

## Kurzban等从**进化论**视角提出另一个定义   
   &emsp;&emsp;**观点**：  
   &emsp;&emsp;为了避免潜在的缺陷伴随群体生存，人们已经**进化了认知适应能力**，允许他们将具有某些特定特征的人排斥到他们的群体之外，即污名化。

## Link等人**重新定义**污名的概念 
+ **观点**:
    + **污名化存在条件**：                 
        - [ ] 人们区分并标签人类的$\color{red}{差异}$ 
        - [ ] 主流群体为了在一定程度上把“我们”从“他们”中分离出来, $\color{red}{将被标签的人置于独特的类别中}$
        - [ ] 被标签的人经历着$\color{red}{不公平的处境}$, 丧失了地位和遭到了歧视 
        - [ ]  只有一个群体有$\color{red}{足够的影响力}$来左右公众对另一个群体态度的时候, 污名才会存在 
      
+ **定义**：   
&emsp;&emsp;是指在一个允许污名各种成分显露的社会情景中, **贴标签,刻板印象,地位丧失**,和**歧视**同时发生的情况。
      
# 2.污名化的典型现象
+ 疾病污名——$\color{grey}{例：艾滋病}$
+ 身份污名——$\color{grey}{例：农民工}$
+ 性别污名——$\color{grey}{例：女博士、女司机}$
+ 职业污名——$\color{grey}{例：公关、保洁}$
+ 种族和地域污名——$\color{grey}{例：河南人、黑人}$

# 3.污名化的作用形式
## 公众污名    
&emsp;&emsp;$\color{red}{一个群体}$将贬低化标签强加在$\color{red}{另一个群体}$之上并加以维持的动态过程。

## 自我污名   
&emsp;&emsp; 某一群体或个体在遭受公众污名贬损之后,在$\color{red}{主观上}$产生的自卑感、自羞感和自责感。被污名群体或个体会因此遭受社会排斥,出现意志消沉、相互敌视、自尊贬损等情绪极化现象。        

## 媒介污名   
&emsp;&emsp;媒介污名通过$\color{red}{报道或传播}$某一特定群体、事物的$\color{red}{负面信息}$实施污名,能够有效改变社会公众对其原有的印象，尤其是网络媒介社会化和自媒体化的技术变革放大了污名效果。

# 4.污名化的发展过程
## 从特殊污名到一般污名
+ 从**受污者的数量**看  
&emsp;&emsp;**传统污名**主要是针对数量有限的*特殊人群*的种族污名、疾病污名。  
&emsp;&emsp;**泛污名化**则除了针对这些特殊群体之外,还存在更大范围、更*一般群体*的普遍污名。

+ 从**污名的内容**看  
&emsp;&emsp;**传统污名**主要关注受污者的*某一具体特质*(如残疾、疾病) 或社会心理现象。  
&emsp;&emsp;**泛污名化**则扩展到社会成员*众多方面的特质*,如认知、情感、行为表现、选择偏好、社会生活等,形成了身份污名、性别污名等。

+ 从**污名的类型**看  
&emsp;&emsp;**传统污名**主要是*个体*污名或某一群体中的*一些个体或成员*的污名。   
&emsp;&emsp;**泛污名化**则从个体扩展到其所在的*组织乃至职业*, 形成组织污名、职业污名。

## 从单向污名到交错污名
&emsp;&emsp;**传统污名**更多的是社会强势群体、主流群体对非强势群体、非主流群体的贬损和侮辱,呈现出*单向度、一元化*的污名关系。   
&emsp;&emsp;**泛污名化**则不仅包括社会强势群体、主流群体对非强势群体、非主流群体的贬损和侮辱,也包括非强势群体、非主流群体对强势群体和主流群体的嘲弄与讽刺。

## 从外显污名到内隐污名
&emsp;&emsp;**传统污名**主要针对的是受污者的身体、精神方面的疾病或其他较为明显的*表面特质*而产生的外显污名。   
&emsp;&emsp;**泛污名化**则在此基础上,主要针对社会成员较为*内在的言语、知识、行为、职业、阶层*等隐匿性特质。

## 常态污名与突发污名并存
&emsp;&emsp;**传统污名**主要是以*常态污名*为主,即污名的对象主要是长时期内一直受到社会普遍污名的现象,如疾病污名(艾滋病)等。    
&emsp;&emsp;**泛污名化**情况下，一些*突发事件*也可能导致个人或组织的污名化,使得最初对于突发事件的污名逐渐延伸到对与之相关的人、群体、组织、机构、制度的污名。$\color{grey}{如}$“三聚氰胺”事件引发民众对所有国产奶粉企业甚至整个食品行业的不信任等。

## 公众污名与自我污名分离
&emsp;&emsp;在**传统污名**中,社会大众在对某一个体或群体进行污名贬损和“贴标签”的同时,受污者自身对污名特质产生自卑、羞愧和耻辱,对公众污名产生一种强烈的主观感应。  
&emsp;&emsp;在**泛污名化过程**中,部分污名者依然会受到公众污名的影响,产生“自我低评价”和“自我低效能”的自我污名,但也出现了部分污名者自我贬低的消极知觉*逐渐淡化*的趋势。

# 5.污名化的影响

>由于不同的文化背景下主流群体对劣势群体有着不同的影响, 污名其他群体的目的不同;不同的污名群体都有自己的独特特点, 主流群体与各污名群体发生作用的规律各不相同,污名各个劣势群体的方式和途径也存在着很大的差异。**因此不同情况下的污名化造成的影响虽有重合的部分，但侧重点仍有所不同。**

以下就$\color{orange}{一般产生的普遍影响}$和$\color{orange}{具体案例}$的不同影响进行分析：

## 普遍影响

+ **破坏社会秩序**
    + **加剧不同群体间的矛盾冲突**   
    &emsp;&emsp;由于污名化现象是社会主流舆论对于特定群体的贴标签行为，污名化现象就很**容易引发相关群体之间的对立情绪**,导致矛盾发生。$\color{grey}{如}$医生群体与患者群体的医患矛盾、城管与小贩群体间的暴力冲突等。

    + **巩固社会刻板成见**       
    &emsp;&emsp;当人们对一个群体有了消极认知,**负面印象很难得到消除并极容易被加深**，因此刻板成见和污名化现象的发生会形成恶性循环。
  
    + **促使道德绑架等其他问题发生**   
    &emsp;&emsp;污名化会引发更多不良效应，**形成错误舆论**，导致发生舆论大反转。不少事件的网络讨论中,一些网民习惯于不谴责加害者,而是对受害方进行污名化。$\color{grey}{如}$被家暴“一定是其出轨在先”,被打者“一定是他先挑衅”等,并以此来讨伐受害人,在言语上对其进行二次伤害。

    + **导致社会关系的失衡**  
    &emsp;&emsp;污名化现象的影响对社会有着**长远**的消极作用。$\color{grey}{如}$社会对于医生的污名化,暴力伤医频发,高考生报考医学专业的人数逐年下滑。其中工作辛苦、待遇差、专业要求高的儿科医生流失更为迅速,儿科医疗资源已显现出极度不足,婴幼儿患病和死亡率有所上升。

+ **对被污名化者产生消极影响**
    + **损害被污名化者的形象**  
    &emsp;&emsp;污名化对于被污名化者的形象毁坏是极为严重的，$\color{grey}{如}$一个企业或者品牌遭受污名化，对于其自身的形象建设是不利的，会导致大众在心中形成一个歪曲不实的不良印象，从而引发多方面的消极影响。

    + **导致群体被排斥和边缘化**   
    &emsp;&emsp;污名化的**最直接**作用就是使污名群体受到社会其他成员的歧视、排斥,包括对群体成员的不公正对待,$\color{grey}{如}$白人歧视黑人。降低群体成员的社会地位,使该群体被边缘化,被孤立,远离社会主流。*伴随着群体被孤立和排斥,群体的话语权和在公众视野中出现的机会也随之减少,使得群体失去被更多人了解、被公众正确认识的机会。*

    + **加剧被污名化者消极情绪**  
    &emsp;&emsp;相较社会其他群体,被污名化群体受到的影响最大。群体成员可能会隐藏自己的群体属性,对自身的认知出现偏差,群体消极情绪增大,减少群体认同感等。

+ **对媒体产生消极影响**
    + **减少媒体公信力**  
    &emsp;&emsp;很多对群体污名化的理由中,存在着失实、夸张的成分,这些报道的存在会消磨媒体的公信力,使大众很难再相信媒体的言论，这无疑会使媒体陷入被动,更难行使自身话语权和舆论引导职责。**短时间内造成舆论引导的滞后和困难,长此以往,还会使媒体的社会作用难以发挥**。
    + **媒体本身也被污名化**   
    &emsp;&emsp;媒体对于其他群体的污名化,通常会遭到群体成员的驳斥和反抗。指责媒体恶意炒作、报道不实等,这些都加剧了传媒群体和被污名群体的矛盾。媒体本身也会被社会舆论贴上负面标签,成为被污名的对象。

## 针对具体案例分析
+ **艾滋病污名化**

> 艾滋病从发现以来就被被认为是极其罪恶的疾病，而只有身负罪恶的人才会得。即使是现在，每每谈起总是让人联想到“肮脏不堪”的行为。

&emsp;&emsp;**影响**
    ```{R, echo=FALSE}
DiagrammeR::grViz("

digraph RmarkDown {
graph [rankdir = LR]
node [shape=rectangle
  style=filled
  color=white
  fillcolor=white
  fontcolor=black
  arrowcolor=red
  alpha=65
  fontname = '楷体']
edge [color = grey]
'影响' -> '对患者的影响'
'影响' -> '对患者家属的影响'
'对患者的影响' -> '降低患者自尊'
'对患者的影响' -> '不愿暴露病情，拒绝求医和接受治疗'
'对患者的影响' -> '已经暴露病情的患者生活上陷入巨大的困境'
'已经暴露病情的患者生活上陷入巨大的困境'->'失去工作或不被雇佣'
'已经暴露病情的患者生活上陷入巨大的困境'->'被亲友所疏远或孤立'
'已经暴露病情的患者生活上陷入巨大的困境'->'租不到房子'
'对患者家属的影响' -> '影响到家庭的脸面, 使整个家庭的社会交往圈变小'
'对患者家属的影响' -> '影响家庭成员间的和睦甚至导致家庭的破裂'
     }
    ", width=800)
```

+  **专家污名化**

> 近几年中国民众对专家的质疑越来越多,嘲讽专家的现象也屡见不鲜,一些网民甚至以“砖家”和“叫兽”等词汇来嘲讽专家群体, 将“专家”污名化。

&emsp;&emsp;**影响**
    ```{R, echo=FALSE}
DiagrammeR::grViz("

digraph RmarkDown {
graph [rankdir = TB]
node [shape=rectangle
  style=filled
  color=white
  fillcolor=white
  fontcolor=black
  arrowcolor=red
  alpha=65
  fontname = '楷体']
edge [color = grey]
'影响' -> '民众对专家产生质疑乃至信任危机'
'影响' -> '误导社会舆论, 激化社会矛盾'
'影响' -> '造成专家与民众的对立'
'误导社会舆论, 激化社会矛盾' -> '引发社会秩序失范'
'造成专家与民众的对立' -> '不利于民众科学素养的提高'
'不利于民众科学素养的提高' -> '阻碍社会发展进步'
     }
    ", width=800)
```

+ **“中国病毒”**

> 美国总统特朗普称新冠病毒为“中国病毒”，试图污名化中国。
   
&emsp;&emsp;**影响**
    ```{R, echo=FALSE}
DiagrammeR::grViz("

digraph RmarkDown {
graph [rankdir = TB]
node [shape=rectangle
  style=filled
  color=white
  fillcolor=white
  fontcolor=black
  arrowcolor=red
  alpha=65
  fontname = '楷体']
edge [color = grey]
'影响' -> '将科学问题政治化'
'影响' -> '助长美国国内的种族仇视情绪'
'将科学问题政治化' -> '抹黑和打压中国'
'助长美国国内的种族仇视情绪' -> '华侨在国外可能受到歧视'
     }
    ", width=600)
```

# 6.关于去污名化的思考
## 每个人或群体都需要对自己传播的信息负责
 &emsp;&emsp;要避免先入为主，要尽量避免将带有个人色彩的观点带入传播活动中，$\color{red}{坚持客观真实原则}$。在网络污名化风向中不应随波逐流，拥有自己的思考。

## 给予一些已经被污名化的个人或群体话语权
 &emsp;&emsp;当一个人或一个群体遭受污名化时，人们往往带着固化思维来评论和看待发生事件。如果被污名化者可以得到话语权，为自己发声，他们将有机会$\color{red}{为自己正名}$，改变人们的固有印象。

## 作为信息接收者的人们也应该提高自身辨别是非的能力
 &emsp;&emsp;自主地形成正确的、稳固的社会认知，不要轻易因为媒体的污名化报道而改变自我认知和价值体系。同时，在知晓热点事件后，大众要$\color{red}{冷静公正地看待}$事件，合理地审视事件所谓的“真相”。
      
      
      
      
      

    
    